name:                ProjectEuler
version:             0.1.0.0
github:              "rvighne/ProjectEuler"
license:             BSD3
author:              "Rohit Vighne"
maintainer:          "rohit.vighne@gmail.com"
copyright:           "2018 Rohit Vighne"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rvighne/ProjectEuler#readme>

dependencies:
- base >= 4.7 && < 5
- array == 0.5.*
- containers == 0.5.*
- split == 0.2.*

library:
  source-dirs: src

executables:
  ProjectEuler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ProjectEuler

tests:
  ProjectEuler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ProjectEuler
